name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-lint-test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap
      - run: pnpm run lint
      - run: pnpm run --if-present test
      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
          commit: "chore: release"
          title: "chore: release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  chromatic:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/bootstrap
      - uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:stories
          exitOnceUploaded: true
          onlyChanged: true
          externals: |
            **/*.css
            pnpm-lock.yaml
            src/tailwind-preset.ts
            tailwind.config.ts
